# Setup
title:        SiteAngle
tagline:      让您的网站永久可被访问，不需要更改域名。最新版2.2.1
desc:
baseurl:      ""
paginate:     1
locale:       "zh-CN"

# About/contact
author:
  name:       SiteAngle
  url:        https://w.url.cn/s/AB6IIYQ

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown


version:
  win64: https://lanzoucloud.lanzous.com/ikZjNe0dlzi
  win32: https://lanzoucloud.lanzous.com/ifnp4e0djhi
  mac: https://lanzoucloud.lanzous.com/iw8N3e0diej
