# Setup
title:        SiteAngle
tagline:      让您的网站永久可被访问，不需要更改域名。最新版2.0.0
desc:
baseurl:      ""
paginate:     1
locale:       "zh-CN"

# About/contact
author:
  name:       SiteAngle
  url:        https://w.url.cn/s/AB6IIYQ

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown


version:
  win64: https://lanzoucloud.lanzous.com/iy92zdrjyle
  win32: https://lanzoucloud.lanzous.com/iYqJCdrk4yd
  mac: https://lanzoucloud.lanzous.com/iWgUndrjtha
