# Setup
title:        SiteAngle
tagline:      让您的网站永久可被访问，不需要更改域名。最新版2.0.0
desc:
baseurl:      ""
paginate:     1
locale:       "zh-CN"

# About/contact
author:
  name:       SiteAngle
  url:        https://siteangel.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown


version:
  win64: https://www.lanzous.com/i6fr6dc
  win32: https://www.lanzous.com/i6fr5wf
  mac: https://www.lanzous.com/i6fr6rg
